# Generated by Django 5.1.5 on 2025-03-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='fecha_pago',
        ),
        migrations.AddField(
            model_name='contrato',
            name='dia_pago',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
